AppBlog/urls.py
from django.urls import path
from .views import (
    authorBlogPanelView, authorBlogPublishView,
    PublicBlogListView, PublicBlogDetailView,
    AuthorBlogCreateView, AuthorBlogUpdateView, AuthorBlogDeleteView,
    HashtagCreateView, HashtagListView, hashtagDetail
)

# namesapce for this app's urls
app_name = "AppBlog"

urlpatterns = [
    # public views
    path("list/", PublicBlogListView.as_view(), name="list"),
    path("detail/<int:pk>", PublicBlogDetailView.as_view(), name="detail"),

    # author views, cud
    path("author/panel", view=authorBlogPanelView, name="panel"),
    path("author/publish/<int:pk>", view=authorBlogPublishView, name="publish"),
    path("author/new/", AuthorBlogCreateView.as_view(), name="create"),
    path("author/edit/<int:pk>", AuthorBlogUpdateView.as_view(), name="update"),
    path("author/delete/<int:pk>", AuthorBlogDeleteView.as_view(), name="delete"),

    # hashtag
    path("hashtag/new", HashtagCreateView.as_view(), name='hashtag_create'),
    path("hashtag/list", HashtagListView.as_view(), name='hashtag_list'),
    path("hashtag/tag=<slug:slug>", view=hashtagDetail, name='hashtag_detail'),
]

SocialMediumProject/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView, TestView

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("accounts/", include("AppAccount.urls")),
    path("blog/", include("AppBlog.urls")),
    path('admin/', admin.site.urls),
    path("test/", TestView.as_view(), name="test"),
    path("debug/", include("debug_toolbar.urls")),
]

AppBlog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.utils.text import slugify


# get custom user model as User
User = get_user_model()


class Blog(models.Model):
    # the author of current post
    author = models.ForeignKey(
        User,   # refer to a custom user model
        on_delete=models.CASCADE
    )
    # title of current post
    title = models.CharField(max_length=64)
    # content of current post
    content = models.TextField(default="")
    # published time
    published_time = models.DateTimeField(null=True, blank=True)
    # created time,
    created_time = models.DateTimeField(auto_now_add=True)
    # last modified time
    last_modified_time = models.DateTimeField(auto_now=True)
    # hashtag
    hashtag = models.ManyToManyField(
        "AppBlog.Hashtag",
        related_name="blogs",       # the name used to refer to current blog from Hashtag
        related_query_name="blogs",  # the name used to look up filter from Hashtag
        through="BlogHashtag"       # the name of intermediate table
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("AppBlog:detail", kwargs={"pk": self.pk})

    def publish(self, *args, **kwargs):
        self.published_time = timezone.now()
        self.save()

    class Meta:
        ordering = ["-last_modified_time",]


class BlogHashtag(models.Model):
    ''' manual intermediate table  '''

    blog = models.ForeignKey(
        "AppBlog.Blog",
        on_delete=models.CASCADE
    )

    hashtag = models.ForeignKey(
        "AppBlog.Hashtag",
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.blog.title

    class Meta:
        unique_together = ("blog", "hashtag")     # unique together


class Hashtag(models.Model):
    # name of hashtag
    name = models.CharField(
        max_length=32,  # less than 32 chars
        unique=True     # must be unique
    )
    slug = models.SlugField(
        unique=True,        # must be unique
        allow_unicode=True,  # accepts Unicode letters
    )

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("AppBlog:hashtag_detail", kwargs={"slug": self.slug})
    
    class Meta:
        ordering = ["name"]     # default ordered by name

AppBlog/forms.py
from django.forms.models import ModelForm
from .models import Blog, Hashtag
from django.forms import CheckboxSelectMultiple


class BlogForm(ModelForm):
    class Meta:
        model = Blog
        fields = ("title", "content", "hashtag")
        widgets = {
            "hashtag": CheckboxSelectMultiple()
        }


class HashtagForm(ModelForm):
    class Meta:
        model = Hashtag
        fields = ("name",)      # must end with comma

AppBlog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .forms import BlogForm, HashtagForm
from .models import Blog, Hashtag

from django.contrib.auth import get_user_model

# region public view


class PublicBlogListView(ListView):
    ''' View of blog list '''
    model = Blog
    extra_context = {"title": "Blog List", "heading": "Blog List"}
    template_name = "AppBlog/blog_list.html"

    def get_queryset(self):
        querySet = super().get_queryset()
        querySet = querySet.filter(published_time__isnull=False)
        return querySet


class PublicBlogDetailView(DetailView):
    ''' View of blog detail '''
    model = Blog
    extra_context = {"title": "Blog Detail", "heading": "Blog Detail"}
    template_name = "AppBlog/blog_detail.html"


class HashtagListView(ListView):
    model = Hashtag
    extra_context = {"title": "All Hashtag", "heading": "All Hashtag"}
    template_name = "AppBlog/hashtag_list.html"

# endregion

# region Author view


def authorBlogPanelView(request):
    ''' panel view of blog '''
    context = {
        "title": "Blog Panel",
        "heading": "Blog Panel",
        "blog_list": Blog.objects.filter(
            author=request.user,
            published_time__isnull=False
        ),
        "draft_list": Blog.objects.filter(
            author=request.user,
            published_time__isnull=True
        )
    }
    template = "AppBlog/blog_panel.html"
    return render(request, template, context)


def authorBlogPublishView(request, pk):
    ''' publish blog '''
    blog = get_object_or_404(Blog, pk=pk)
    blog.publish()
    return redirect("AppBlog:panel")


class AuthorBlogCreateView(LoginRequiredMixin, CreateView):
    ''' Blog create for author '''
    model = Blog
    form_class = BlogForm
    extra_context = {"title": "Blog New", "heading": "Blog New"}
    template_name = "AppBlog/blog_form.html"

    # customizes process when form is valid.
    def form_valid(self, form):
        print(self.request.user.username)
        self.object = form.save(commit=False)   # gets the object from the form
        # assigns the request user to user field
        self.object.author = self.request.user
        self.object.save()                      # saves the Blog object
        return super().form_valid(form)         # calls the parent form_valid()


class AuthorBlogUpdateView(LoginRequiredMixin, UpdateView):
    ''' Blog update for author '''
    model = Blog
    form_class = BlogForm
    extra_context = {"title": "Blog Edit", "heading": "Blog Edit"}
    template_name = "AppBlog/blog_form.html"


class AuthorBlogDeleteView(LoginRequiredMixin, DeleteView):
    ''' Blog delete for author '''
    model = Blog
    extra_context = {"title": "Blog Delete", "heading": "Blog Delete"}
    success_url = reverse_lazy("AppBlog:list")


class HashtagCreateView(LoginRequiredMixin, CreateView):
    model = Hashtag
    form_class = HashtagForm
    extra_context = {"title": "Hashtag New", "heading": "Hashtag New"}
    template_name = "AppBlog/hashtag_form.html"

    # customizes process when form is valid.
    def form_valid(self, form):
        self.object = form.save(commit=False)   # gets the object from the form
        # assigns the request user to user field
        self.object.name = self.object.name.strip()  # strip the hashtag name
        self.object.save()                      # saves the Blog object
        return super().form_valid(form)         # calls the parent form_valid()


def hashtagDetail(request, slug):
    ''' public view for each hashtag '''
    hashtag = get_object_or_404(Hashtag, slug=slug)

    context = {
        "title": f"Hashtag:{hashtag.name}",
        "heading": f"Hashtag:{hashtag.name}",
        # find blogs with hashtag
        "blog_list": Blog.objects.filter(hashtag=hashtag, published_time__isnull=False)
    }
    print(context)
    template = "AppBlog/hashtag_detail.html"
    return render(request, template, context)


# endregion

AppBlog/templates/AppBlog/blog_confirm_delete.html
{% extends "layout/base.html" %} {% block header %}
<header class="pt-4">
  <h1 class="text-body-secondary">{{heading}}</h1>
  <hr />
</header>
{% endblock %} {% block main %}

<div class="container p-4">
  <div class="row">
    <div class="col-9 ">
      <form method="post">
        {% csrf_token %}
        <p class="fs-5 vh-50">
          Are you sure you want to delete the following? <br />
          <u>{{ object }} </u>
        </p>
        {{ form }}
        <hr />
        <div class="d-flex">
          <a
            href="{% url 'AppBlog:detail' pk=object.pk %}"
            class="btn btn-outline-secondary rounded-pill"
            >Back</a
          >
          <button
            class="btn btn-outline-danger rounded-pill ms-auto"
            type="submit"
          >
            Confirm
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock %} {% block js %} {% endblock %}

AppBlog/templates/AppBlog/blog_detail.html
{% extends "layout/base.html" %} {% block header %}
<header></header>
{% endblock %} {% block main %}

<div class="container p-4">
  <div class="row">
    <div class="col-9">
      <h1 class="text-body-secondary text-center">{{blog.title|upper}}</h1>
      <hr />
      <!-- author -->
      <div class="d-flex justify-content-center align-items-center">
        <i class="bi bi-at fs-4"></i>
        <a href="#">{{blog.author}}</a>
        <small class="ms-3">
          {{blog.last_modified_time|date:'Y-m-d G:i '}}</small
        >
      </div>

      <!-- content -->
      <div class="">{{blog.content|safe}}</div>

      <!-- hashtag -->
      <div class="d-flex justify-content-start">
        {% for hashtag in blog.hashtag.all %}
        <a
          class="btn btn-sm btn-info rounded-pill mx-2"
          href="{% url 'AppBlog:hashtag_detail' hashtag.slug %}"
        >
          #{{hashtag}}
        </a>
        {% endfor %}
      </div>

      <hr />
      <div class="d-flex py-4 my-3">
        {% if user.is_authenticated and user.username == blog.author.username %}
        <a
          href="{% url 'AppBlog:panel' %}"
          class="btn btn-outline-secondary rounded-pill"
          >Back</a
        >
        <a
          href="{% url 'AppBlog:update' pk=blog.pk %}"
          class="btn btn-outline-primary rounded-pill ms-auto"
          >update</a
        >
        <a
          href="{% url 'AppBlog:delete' pk=blog.pk %}"
          class="btn btn-outline-danger rounded-pill ms-2"
          >Delete</a
        >
        {% else %}
        <a
          href="{% url 'home' %}"
          class="btn btn-outline-secondary rounded-pill"
          >Back</a
        >
        {% endif %}
      </div>
    </div>
  </div>
</div>

{% endblock %} {% block js %} {% endblock %}

AppBlog/templates/AppBlog/blog_form.html
{% extends "layout/base.html" %} {% block header %}
<header class="pt-4">
  <h1 class="text-body-secondary">{{heading}}</h1>
  <hr />
</header>
{% endblock %} {% block main %} {% load django_bootstrap5 %}

<div class="container p-3">
  <div class="row">
    <div class="col-9 py-2">
      <form method="post" novalidate>
        {% csrf_token %} {% bootstrap_form form %}
        <a
          class="btn btn-sm btn-warning rounded-pill"
          href="{% url 'AppBlog:hashtag_create' %}"
          >New Hashtag</a
        >
        <hr class="my-3" />
        <div class="d-flex pt-3 pb-5">
          <a
            class="btn btn-outline-secondary rounded-pill"
            href="{% url 'AppBlog:panel' %}"
            >Back</a
          >
          <button
            class="btn btn-outline-secondary rounded-pill ms-auto"
            type="reset"
          >
            Reset
          </button>
          <button
            class="btn btn-outline-primary rounded-pill ms-3"
            type="submit"
          >
            {% if form.instance.pk %} Update {% else %} Save {% endif %}
          </button>
        </div>
      </form>
    </div>
    {% endblock %} {% block js %}
    <script>
      tinymce.init({
        selector: "textarea",
      });
    </script>
    {% endblock %}
  </div>
</div>

AppBlog/templates/AppBlog/blog_list.html
{% extends "layout/base.html" %} {% block header %}
<header class="pt-4">
  <h2>{{heading}}</h2>
  <hr />
</header>
{% endblock %} {% block main %}
<div class="container py-3">
  <div class="row">
    {% for blog in blog_list %}
    <div class="col-md-8 py-4 border-bottom">
      <div class="d-flex align-items-center">
        <i class="bi bi-at fs-4"></i>
        <a href="#">{{blog.author}}</a>
        <small class="ms-3"> {{blog.last_modified_time|date:'Y-m-d G:i '}}</small>
      </div>

      <h4 class="mb-1">
        <a
          class="text-body-secondary"
          href="{% url 'AppBlog:detail' blog.pk %}"
        >
          {{blog.title}}
        </a>
      </h4>

      <div class="py-1">
        {{blog.content|safe|linebreaks|truncatewords_html:64}}
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %} {% block js %} {% endblock %}

AppBlog/templates/AppBlog/blog_panel.html
{% extends "layout/base.html" %} {% block header %}
<header class="pt-4">
  <h1 class="text-body-secondary text-center d-flex">
    <span> {{heading}} </span>
    <a
      class="btn btn-outline-primary rounded-pill align-self-center ms-auto shadow"
      href="{% url 'AppBlog:create' %}"
    >
      New Blog</a
    >
  </h1>
  <hr />
</header>
{% endblock %} {% block main %}
<div class="container text-body-secondary">
  <div class="row">
    <div class="col-12">
      <div class="container">
        <p class="fs-5">Published blog: <b>{{blog_list.count}}</b></p>
        {% if blog_list %}
        <table
          class="table table-striped table-hover text-center border border-2 shadow"
        >
          <thead class="fw-bold">
            <td>Title</td>
            <td>Published Time</td>
            <td>Delete</td>
          </thead>
          <tbody>
            {% for blog in blog_list %}
            <tr>
              <td class="text-start">
                <a href="{% url 'AppBlog:detail' blog.pk %}">{{blog.title}}</a>
              </td>
              <td>{{blog.published_time|date:'y-m-d H:i'}}</td>
              <td>
                <a
                  class="fs-5 text-danger bi bi-trash"
                  href="{% url 'AppBlog:delete' blog.pk %}"
                >
                </a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        {% else %}
        <p>No published blog.</p>
        {% endif %}
      </div>
      <hr />
      <div class="container">
        <p class="fs-5">Draft: <b>{{draft_list.count}}</b></p>
        {% if draft_list %}
        <table
          class="table table-striped table-hover text-center border border-2 shadow"
        >
          <thead class="fw-bold">
            <td>Title</td>
            <td>Created Time</td>
            <td>Last Updated Time</td>
            <td>Publish</td>
            <td>Delete</td>
          </thead>
          <tbody>
            {% for draft in draft_list %}
            <tr>
              <td class="text-start">
                <a href="{% url 'AppBlog:detail' draft.pk %}"
                  >{{draft.title}}</a
                >
              </td>
              <td>{{draft.created_time|date:'y-m-d H:i'}}</td>
              <td>{{draft.last_modified_time|date:'y-m-d H:i'}}</td>
              <td>
                <a
                  class="fs-5 text-primary bi bi-file-arrow-up"
                  href="{% url 'AppBlog:publish' draft.pk %}"
                >
                </a>
              </td>
              <td>
                <a
                  class="fs-5 text-danger bi bi-trash"
                  href="{% url 'AppBlog:delete' draft.pk %}"
                >
                </a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        {% else %}
        <p>No draft.</p>
        {% endif %}
      </div>
    </div>
  </div>
</div>

{% endblock %} {% block js %} {% endblock %}

AppBlog/templates/AppBlog/hashtag_detail.html
{% extends "layout/base.html" %} {% block header %}
<header class="pt-4">
  <h1 class="text-body-secondary">{{heading}}</h1>
  <hr />
</header>
{% endblock %} {% block main %}

<div class="container">
  <div class="row pb-4">
    <div class="col-12">
      {% if blog_list %}
      <table
        class="table table-striped table-hover text-center border border-2 shadow"
      >
        <thead class="fw-bold">
          <td>Title</td>
          <td>Author</td>
          <td>Published Time</td>
        </thead>
        <tbody>
          {% for blog in blog_list %}
          <tr>
            <td class="text-start">
              <a href="{% url 'AppBlog:detail' blog.pk %}">{{blog.title}}</a>
            </td>
            <td>{{blog.author}}</td>
            <td>{{blog.published_time|date:'y-m-d H:i'}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      {% else %}
      <p class="lead fs-4">No blog relates to this hashtag.</p>
      {% endif %}
    </div>
  </div>

  <div class="row py-2"></div>
</div>

<hr class="py-2" />

<div class="d-flex py-2">
  {% if user.is_authenticated %}
  <a
    href="{% url 'AppBlog:hashtag_list' %}"
    class="btn btn-outline-secondary rounded-pill"
    >Back</a
  >
  {% else %}
  <a href="{% url 'home' %}" class="btn btn-outline-secondary rounded-pill"
    >Back</a
  >
  {% endif %}
</div>

{% endblock %} {% block js %} {% endblock %}

AppBlog/templates/AppBlog/hashtag_form.html
{% extends "layout/base.html" %} {% block header %}
<header>
  <h1 class="text-body-secondary text-center">{{heading}}</h1>
  <hr />
</header>
{% endblock %} {% block main %} {% load django_bootstrap5 %}
<form method="post" novalidate>
  {% csrf_token %}
  <div class="row">
    <div class="col-12 my-2">{% bootstrap_form form %}</div>
    <div class="col-12 my-2">
      <div class="d-flex">
        <a
          class="btn btn-outline-secondary rounded-pill"
          href="{% url 'AppBlog:panel' %}"
          >Back</a
        >
        <button
          class="btn btn-outline-secondary rounded-pill ms-auto"
          type="reset"
        >
          Reset
        </button>
        <button class="btn btn-outline-primary rounded-pill ms-3" type="submit">
          New Hashtag
        </button>
      </div>
    </div>
  </div>
</form>
{% endblock %} {% block js %}
<script>
  tinymce.init({
    selector: "textarea",
  });
</script>
{% endblock %}

AppBlog/templates/AppBlog/hashtag_list.html
{% extends "layout/base.html" %} {% block header %}
<header class="p-4">
  <div class="d-flex">
    <h1 class="text-body-secondary text-center">{{heading}}</h1>
    <a
      class="btn btn-warning rounded-pill mx-3 align-self-center ms-auto"
      href="{% url 'AppBlog:hashtag_create' %}"
      >New Hashtag</a
    >
  </div>
  <hr />
</header>
{% endblock %} {% block main %}

<div class="container">
  <div class="d-flex">
    {% for hashtag in hashtag_list %}

    <a
      class="btn btn-primary btn-sm rounded-pill mx-2"
      href="{% url 'AppBlog:hashtag_detail' hashtag.slug %}"
    >
      {{hashtag.name}}
    </a>
    {% endfor %}
  </div>
</div>

{% endblock %} {% block js %} {% endblock %}