AppAccount/urls.py
from django.urls import path
from .views import SignupView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

app_name = "AppAccount"

urlpatterns = [
    path("signup/", SignupView.as_view(), name="signup"),
    path("login/", LoginView.as_view(
        template_name="AppAccount/login.html",
        extra_context={"title": "Login", "heading": "Login"}
    ), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("profile/", login_required(TemplateView.as_view(
        template_name="AppAccount/profile.html",
        extra_context={"title": "User Profile", "heading": "User Profile"}
    )), name="profile"),
]

AppBlog/urls.py
from django.urls import path
from .views import (
    authorBlogPanelView, authorBlogPublishView,
    PublicBlogListView, PublicBlogDetailView,
    AuthorBlogCreateView, AuthorBlogUpdateView, AuthorBlogDeleteView,
    HashtagCreateView, HashtagListView, hashtagDetail
)

# namesapce for this app's urls
app_name = "AppBlog"

urlpatterns = [
    # public views
    path("list/", PublicBlogListView.as_view(), name="list"),
    path("detail/<int:pk>", PublicBlogDetailView.as_view(), name="detail"),

    # author views, cud
    path("author/panel", view=authorBlogPanelView, name="panel"),
    path("author/publish/<int:pk>", view=authorBlogPublishView, name="publish"),
    path("author/new/", AuthorBlogCreateView.as_view(), name="create"),
    path("author/edit/<int:pk>", AuthorBlogUpdateView.as_view(), name="update"),
    path("author/delete/<int:pk>", AuthorBlogDeleteView.as_view(), name="delete"),

    # hashtag
    path("hashtag/new", HashtagCreateView.as_view(), name='hashtag_create'),
    path("hashtag/list", HashtagListView.as_view(), name='hashtag_list'),
    path("hashtag/tag=<slug:slug>", view=hashtagDetail, name='hashtag_detail'),
]

SocialMediumProject/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView, TestView

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("accounts/", include("AppAccount.urls")),
    path("blog/", include("AppBlog.urls")),
    path('admin/', admin.site.urls),
    path("test/", TestView.as_view(), name="test"),
    path("debug/", include("debug_toolbar.urls")),
]

AppAccount/models.py
from django.db import models
from django.contrib.auth import models


class UserAccount(models.User, models.PermissionsMixin):
    ''' custom user class '''
    # multiple inheritance
    # User class: to represent registered users of website
    # Permission Class: an abstract model that has attributes and methods to cutomize a user model
    def __str__(self):
        # self.username is a attribute of the super class User.
        return self.username

AppAccount/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.forms import TextInput, PasswordInput
from django.utils.translation import gettext_lazy as _

from . import models


class UserSignupForm(UserCreationForm):
    ''' a custom form for signup '''
    class Meta:
        model = models.UserAccount
        fields = ("username", "password1", "password2")
        # get_user_model(): return the currently active user model – the custom user model if one is specified, or User otherwise.
        model = get_user_model()
   

AppAccount/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView
from .forms import UserSignupForm


class SignupView(CreateView):
    form_class = UserSignupForm
    success_url = reverse_lazy("AppAccount:login")
    template_name = "AppAccount/signup.html"
    extra_context = {"title": "Sign up", "heading": "Sign up for free"}

AppAccount/templates/AppAccount/login.html
{% extends "layout/base.html" %} {% block header %}
<header>
  <h1 class="heading text-center">{{heading}}</h1>
  <hr />
</header>
{% endblock %} {% block main %}
<div class="row p-3 m-3">
  <div class="col-4 px-0 mx-auto">
    {% if form.errors %}
    {% endif %} {% load django_bootstrap5 %}
    <form method="post">
      {% csrf_token %} {% bootstrap_form form %}
      <div class="row py-3">
        <button class="btn btn-primary w-100 py-2 my-1" type="submit">
          Login
        </button>
        <a
          class="btn btn-outline-secondary w-100 py-2 my-1"
          href="{% url 'home' %}"
          >Cancel</a
        >
        <input type="hidden" name="next" value="{{ next }}" />
      </div>
    </form>

    <hr />
    <p class="text-body-secondary pb-3">
      Do not have an account?
      <a class="text-body-secondary" href="{% url 'AppAccount:signup' %}"
        >Signup</a
      >
    </p>
  </div>
</div>

{% endblock %} {% block js %} {% endblock %}

AppAccount/templates/AppAccount/profile.html
{% extends "layout/base.html" %} {% block header %}
<header>
  <h1 class="heading text-center">{{heading}}</h1>
  <hr />
</header>
{% endblock %} {% block main %} {% endblock %} {% block js %} {% endblock %}

AppAccount/templates/AppAccount/signup.html
{% extends "layout/base.html" %} {% block header %}
<header>
  <h1 class="heading text-center">{{heading}}</h1>
  <hr />
</header>
{% endblock %} {% block main %}
<div class="row p-4">
  <div class="col-8 mx-auto">
    {% load django_bootstrap5 %}
    <form method="post">
      {% csrf_token %} {%bootstrap_form form%}
      <div class="d-flex py-3">
        <a class="btn btn-secondary rounded-pill" href="{% url 'home' %}"
          >Cancel</a
        >
        <button
          class="btn btn-outline-secondary rounded-pill ms-auto"
          type="reset"
        >
          Reset
        </button>
        <button class="btn btn-primary rounded-pill ms-3" type="submit">
          Sign up
        </button>
      </div>
    </form>
  </div>
</div>

{% endblock %} {% block js %} {% endblock %}