AppBlog/urls.py
from django.urls import path
from .views import (
    authorBlogPanelView, authorBlogPublishView,
    PublicBlogListView, PublicBlogDetailView,
    AuthorBlogCreateView, AuthorBlogUpdateView, AuthorBlogDeleteView,
    HashtagCreateView, HashtagListView, hashtagDetail
)

# namesapce for this app's urls
app_name = "AppBlog"

urlpatterns = [
    # public views
    path("list/", PublicBlogListView.as_view(), name="list"),
    path("detail/<int:pk>", PublicBlogDetailView.as_view(), name="detail"),

    # author views, cud
    path("author/panel", view=authorBlogPanelView, name="panel"),
    path("author/publish/<int:pk>", view=authorBlogPublishView, name="publish"),
    path("author/new/", AuthorBlogCreateView.as_view(), name="create"),
    path("author/edit/<int:pk>", AuthorBlogUpdateView.as_view(), name="update"),
    path("author/delete/<int:pk>", AuthorBlogDeleteView.as_view(), name="delete"),

    # hashtag
    path("hashtag/new", HashtagCreateView.as_view(), name='hashtag_create'),
    path("hashtag/list", HashtagListView.as_view(), name='hashtag_list'),
    path("hashtag/tag=<slug:slug>", view=hashtagDetail, name='hashtag_detail'),
]

SocialMediumProject/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView, TestView

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("accounts/", include("AppAccount.urls")),
    path("blog/", include("AppBlog.urls")),
    path('admin/', admin.site.urls),
    path("test/", TestView.as_view(), name="test"),
    path("debug/", include("debug_toolbar.urls")),
]

AppBlog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.utils.text import slugify


# get custom user model as User
User = get_user_model()


class Blog(models.Model):
    # the author of current post
    author = models.ForeignKey(
        User,   # refer to a custom user model
        on_delete=models.CASCADE
    )
    # title of current post
    title = models.CharField(max_length=64)
    # content of current post
    content = models.TextField(default="")
    # published time
    published_time = models.DateTimeField(null=True, blank=True)
    # created time,
    created_time = models.DateTimeField(auto_now_add=True)
    # last modified time
    last_modified_time = models.DateTimeField(auto_now=True)
    # hashtag
    hashtag = models.ManyToManyField(
        "AppBlog.Hashtag",
        related_name="blogs",       # the name used to refer to current blog from Hashtag
        related_query_name="blogs",  # the name used to look up filter from Hashtag
        through="BlogHashtag"       # the name of intermediate table
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("AppBlog:detail", kwargs={"pk": self.pk})

    def publish(self, *args, **kwargs):
        self.published_time = timezone.now()
        self.save()

    class Meta:
        ordering = ["-last_modified_time",]


class BlogHashtag(models.Model):
    ''' manual intermediate table  '''

    blog = models.ForeignKey(
        "AppBlog.Blog",
        on_delete=models.CASCADE
    )

    hashtag = models.ForeignKey(
        "AppBlog.Hashtag",
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.blog.title

    class Meta:
        unique_together = ("blog", "hashtag")     # unique together


class Hashtag(models.Model):
    # name of hashtag
    name = models.CharField(
        max_length=32,  # less than 32 chars
        unique=True     # must be unique
    )
    slug = models.SlugField(
        unique=True,        # must be unique
        allow_unicode=True,  # accepts Unicode letters
    )

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("AppBlog:hashtag_detail", kwargs={"slug": self.slug})
    
    class Meta:
        ordering = ["name"]     # default ordered by name

templates/index.html
{% extends "layout/base.html" %} {% block header %}
<header>
  <h1 class="heading text-center">{{heading}}</h1>
  <hr />
</header>
{% endblock %} {% block main %}
<div class="container py-3">
  <div class="row">
    <div class="col-md-9">
      <!-- this is a meta html. It will be used in blog list view both for visitor and author  -->
      <div class="container">
        <div class="row">
          {% for blog in blog_list %}
          <div class="col-12 py-3 border-bottom">
            <h2>
              {% if user.is_authenticated %}
              <a
                class="text-body-secondary"
                href="{% url 'AppBlog:detail' blog.pk %}"
              >
                {{blog.title}}</a
              >
              {% else %}
              <a
                class="text-body-secondary"
                href="{% url 'AppBlog:detail' pk=blog.pk %}"
              >
                {{blog.title}}</a
              >
              {% endif %}
            </h2>
            <small class="fs-6 text-body-secondary mb-2">
              {% if user.is_authenticated %} By
              <a href="#">{{blog.author}}</a> {% else %} By
              <a href="#">{{blog.author}}</a>
              {% endif %} {{blog.last_modified_time|date:'Y-m-d G:i '}}
            </small>
            <div class="py-3">{{blog.content|safe|truncatewords_html:64}}</div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %} {% block js %} {% endblock %}

templates/test.html
{% extends "layout/base.html" %} {% block header %}
<header>
  <h1>sss</h1>
  <hr />
</header>
{% endblock %} {% block main %} {% endblock %} {% block js %}
<script></script>
{%endblock%}