AppAccount/urls.py
from django.urls import path
from .views import SignupView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

app_name = "AppAccount"

urlpatterns = [
    path("signup/", SignupView.as_view(), name="signup"),
    path("login/", LoginView.as_view(
        template_name="AppAccount/login.html",
        extra_context={"title": "Login", "heading": "Login"}
    ), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("profile/", login_required(TemplateView.as_view(
        template_name="AppAccount/profile.html",
        extra_context={"title": "User Profile", "heading": "User Profile"}
    )), name="profile"),
]

AppBlog/urls.py
from django.urls import path
from .views import (
    authorBlogPanelView, authorBlogPublishView,
    PublicBlogListView, PublicBlogDetailView,
    AuthorBlogCreateView, AuthorBlogUpdateView, AuthorBlogDeleteView,
    HashtagCreateView, HashtagListView, hashtagDetail
)

# namesapce for this app's urls
app_name = "AppBlog"

urlpatterns = [
    # public views
    path("list/", PublicBlogListView.as_view(), name="list"),
    path("detail/<int:pk>", PublicBlogDetailView.as_view(), name="detail"),

    # author views, cud
    path("author/panel", view=authorBlogPanelView, name="panel"),
    path("author/publish/<int:pk>", view=authorBlogPublishView, name="publish"),
    path("author/new/", AuthorBlogCreateView.as_view(), name="create"),
    path("author/edit/<int:pk>", AuthorBlogUpdateView.as_view(), name="update"),
    path("author/delete/<int:pk>", AuthorBlogDeleteView.as_view(), name="delete"),

    # hashtag
    path("hashtag/new", HashtagCreateView.as_view(), name='hashtag_create'),
    path("hashtag/list", HashtagListView.as_view(), name='hashtag_list'),
    path("hashtag/tag=<slug:slug>", view=hashtagDetail, name='hashtag_detail'),
]

SocialMediumProject/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView, TestView

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("accounts/", include("AppAccount.urls")),
    path("blog/", include("AppBlog.urls")),
    path('admin/', admin.site.urls),
    path("test/", TestView.as_view(), name="test"),
    path("debug/", include("debug_toolbar.urls")),
]

templates/layout/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{title}}</title>

    <!-- bootstrap -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
      crossorigin="anonymous"
    ></script>

    <!-- google font -->
    <link
      href="https://fonts.googleapis.com/css2?family=Playfair+Display&family=Roboto&family=Work+Sans&display=swap"
      rel="stylesheet"
    />

    <!-- icon -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css"
    />

    <!-- jquery -->
    <script
      src="https://cdn.jsdelivr.net/npm/jquery@3.7.0/dist/jquery.min.js"
      integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g="
      crossorigin="anonymous"
    ></script>

    <!-- TinyMCE editor -->
    <script
      src="https://cdn.tiny.cloud/1/vy5wrj8ki5mcju47s2qsm9wb75q4yt6cerdf7e58o6iy0su4/tinymce/6/tinymce.min.js"
      referrerpolicy="origin"
    ></script>

    <!-- custom css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />

    <!-- custom js -->
    <!-- <link rel="stylesheet" href="{% static 'js/main.js' %}" /> -->
  </head>
  <body>
    <!-- navbar -->
    {% include "layout/navbar.html" %}
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-2 col-md-1 p-0 border-end border-bottom border-1">
          <!-- sidebar -->
          {% include "layout/sidebar.html" %}
        </div>
        <div class="col-lg-10 col-md-11">
          <!-- main -->
          <main>
            {% block header %}{% endblock %} {% block main %}{% endblock %}
          </main>
        </div>
      </div>
    </div>
    {% block js %}{% endblock %}
  </body>
</html>

templates/layout/dashboard_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{title}}</title>

    <!-- bootstrap -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
      crossorigin="anonymous"
    ></script>

    <!-- google font -->
    <link
      href="https://fonts.googleapis.com/css2?family=Playfair+Display&family=Roboto&family=Work+Sans&display=swap"
      rel="stylesheet"
    />

    <!-- icon -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css"
    />

    <!-- jquery -->
    <script
      src="https://cdn.jsdelivr.net/npm/jquery@3.7.0/dist/jquery.min.js"
      integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g="
      crossorigin="anonymous"
    ></script>

    <!-- TinyMCE editor -->
    <script
      src="https://cdn.tiny.cloud/1/vy5wrj8ki5mcju47s2qsm9wb75q4yt6cerdf7e58o6iy0su4/tinymce/6/tinymce.min.js"
      referrerpolicy="origin"
    ></script>

    <!-- custom css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />

    <!-- custom js -->
    <!-- <link rel="stylesheet" href="{% static 'js/main.js' %}" /> -->
  </head>
  <body>
    <main class="container-fluid p-0">
      <div class="row" style="height: 100vh">
        <div class="col-2 p-0">{% include "layout/side_nav.html" %}</div>
        <div class="col-10 px-5">
          {% block header %}{% endblock %} {% block main %}{% endblock %}
        </div>
      </div>
    </main>
  </body>
</html>

templates/layout/nav.html
<nav
  class="navbar navbar-expand-lg bg-body-tertiary fixed-top"
  data-bs-theme="dark"
>
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">
      <i class="bi bi-stars text-warning"></i>
      Argus
    </a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      </ul>

      {% if not user.is_authenticated %}
      <a class="btn btn-sm btn-warning" href="{% url 'accounts:login' %}"
        >Login</a
      >
      {% else %}
      <ul class="navbar-nav mb-2 mb-lg-0">
        <li class="nav-item dropstart">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            <i class="bi bi-person-circle"></i>
          </a>
          <ul class="dropdown-menu">
            <li><h6 class="dropdown-header">{{user.username}}</h6></li>
            <li>
              <a class="dropdown-item" href="{% url 'accounts:profile' %}"
                >Profile</a
              >
            </li>
            <li><hr class="dropdown-divider" /></li>
            <li>
              <a class="dropdown-item" href="{% url 'accounts:logout' %}"
                >Logout</a
              >
            </li>
          </ul>
        </li>
      </ul>
      {% endif %}
    </div>
  </div>
</nav>

templates/layout/navbar.html
<nav
  class="navbar navbar-expand-lg bg-light-subtle border-bottom border-2 vh-10 sticky-top shadow-sm"
>
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">
      <i class="bi bi-journal-bookmark"></i>
      Blog Project</a
    >
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <!-- <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li> -->
      </ul>
      <!-- management panel -->
      {% if user.is_authenticated %}
      <ul class="navbar-nav mb-2 mb-lg-0">
        <span class="navbar-text"> Hello, {{user.username}} </span>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'AppAccount:profile' %}">
            <u>Profile Panel</u>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'AppBlog:panel' %}">
            <u>Blog Panel</u>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'AppAccount:logout' %}">
            <u>Signout</u>
          </a>
        </li>
      </ul>
      {% else %}
      <a class="btn btn-sm btn-warning" href="{% url 'AppAccount:login' %}">
        Signin
      </a>
      {% endif %}
    </div>
  </div>
</nav>

templates/layout/sidebar.html
<div
  class="d-flex flex-column flex-shrink-0 p-3 vh-90 position-relative"
  style="min-height: 90vh"
>
  <ul class="nav nav-pills flex-column mb-auto">
    <li class="nav-item">
      <a
        class="nav-link link-secondary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover p-2 ms-3"
        href="{% url 'home' %}"
      >
        <i class="bi bi-house-door fs-5 me-2"></i>
        Home
      </a>
    </li>
    <li class="nav-item">
      {% if user.is_authenticated %}
      <a
        class="nav-link link-secondary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover p-2 ms-3"
        href="{% url 'AppAccount:profile'  %}"
      >
        <i class="bi bi-gear fs-5 me-2"></i>
        Profile
      </a>
      {% endif %}
    </li>
    <hr />
    <li class="nav-item">
      <a
        class="nav-link link-secondary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover p-2 ms-3"
        href="{% url 'AppBlog:list'  %}"
      >
        <i class="bi bi-file-earmark-text fs-5 me-2"></i>
        Blog
      </a>
    </li>
    <li class="nav-item">
      <a
        class="nav-link link-secondary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover p-2 ms-3"
        href="{% url 'AppBlog:hashtag_list'  %}"
      >
        <i class="bi bi-hash fs-5 me-2"></i>
        Hashtag
      </a>
    </li>
  </ul>
  {% if user.is_authenticated %}
  <hr />
  <div class="dropdown ms-4">
    <a
      href="#"
      class="d-flex align-items-center text-body-secondary text-decoration-none dropdown-toggle"
      data-bs-toggle="dropdown"
      aria-expanded="false"
    >
      <strong>{{user.username}}</strong>
    </a>
    <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
      <li>
        <a class="dropdown-item" href="{% url 'AppAccount:profile' %}"
          >Profile</a
        >
      </li>
      <li><hr class="dropdown-divider" /></li>
      <li>
        <a class="dropdown-item" href="{% url 'AppAccount:logout' %}">
          Sign out
        </a>
      </li>
    </ul>
  </div>
  {% endif %}
</div>